# Eksperimen MSML - Credit Scoring
Notebook ini memuat data loading, EDA, dan preprocessing manual sesuai template submission.

Oleh: Muhammad Rifqy Saputra (muris11)

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
raw_path = Path('../namadataset_raw/credit_scoring_raw.csv')
df = pd.read_csv(raw_path)
df.head()

   age      income  loan_amount  employment_years home_ownership marital_status  late_payments  target
0   24  11664951.0    4337511.0               6.0           rent        married            0.0       1
1   51   9392621.0    3460053.0               7.0           rent         single            0.0       1
2   46   8603413.0    2842635.0              18.0            own         single            1.0       1
3   38   6410866.0    3418531.0              16.0       mortgage        married            2.0       1
4   37   4813293.0    5341215.0              17.0       mortgage         single            2.0       1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               300 non-null    int64
 1   income            288 non-null    float64
 2   loan_amount       288 non-null    float64
 3   employment_years  288 non-null    float64
 4   home_ownership    288 non-null    object
 5   marital_status    300 non-null    object
 6   late_payments     300 non-null    float64
 7   target            300 non-null    int64
dtypes: float64(4), int64(2), object(2)
memory usage: 18.9+ KB

In [4]:
df.describe(include='all').T

                  count unique     top freq          mean            std        min         25%        50%          75%         max
age               300.0    NaN     NaN  NaN     39.953333      10.678949       20.0       32.00       40.0        49.00        59.0
income            288.0    NaN     NaN  NaN  7925803.291667  2876927.042355  2000091.0  5689633.00  8888149.0  10403127.75  16262668.0
loan_amount       288.0    NaN     NaN  NaN  2949026.625000  1224237.537314   200000.0  2154859.00  2896083.0   3698877.50   6117208.0
employment_years  288.0    NaN     NaN  NaN      9.565972       5.698282        0.0        5.00        9.5        14.25        19.0
home_ownership      288      3    rent  121           NaN            NaN        NaN         NaN        NaN          NaN         NaN
marital_status      300      2  single  164           NaN            NaN        NaN         NaN        NaN          NaN         NaN
late_payments     300.0    NaN     NaN  NaN      1.153333       1.354970        0.0        0.00        1.0         2.00         6.0
target            300.0    NaN     NaN  NaN      0.853333       0.354358        0.0        1.00        1.0         1.00         1.0

In [5]:
df.isnull().sum()

age                  0
income              12
loan_amount         12
employment_years    12
home_ownership      12
marital_status       0
late_payments        0
target               0
dtype: int64

In [6]:
df['target'].value_counts(normalize=True)

target
1    0.853333
0    0.146667
Name: proportion, dtype: float64

In [7]:
processed = df.copy()
for col in ['age','income','loan_amount','employment_years','late_payments']:
    processed[col] = pd.to_numeric(processed[col], errors='coerce')
    processed[col] = processed[col].fillna(processed[col].median())
for col in ['home_ownership','marital_status']:
    processed[col] = processed[col].astype('string').fillna('unknown').str.strip().str.lower()
    mode_value = processed[col].mode().iloc[0] if not processed[col].mode().empty else 'unknown'
    processed[col] = processed[col].replace({'<NA>': mode_value}).fillna(mode_value)
processed.head()

   age      income  loan_amount  employment_years home_ownership marital_status  late_payments  target
0   24  11664951.0    4337511.0               6.0           rent        married            0.0       1
1   51   9392621.0    3460053.0               7.0           rent         single            0.0       1
2   46   8603413.0    2842635.0              18.0            own         single            1.0       1
3   38   6410866.0    3418531.0              16.0       mortgage        married            2.0       1
4   37   4813293.0    5341215.0              17.0       mortgage         single            2.0       1

In [8]:
out_path = Path('namadataset_preprocessing/credit_scoring_preprocessing.csv')
out_path.parent.mkdir(parents=True, exist_ok=True)
processed.to_csv(out_path, index=False)
out_path

PosixPath('namadataset_preprocessing/credit_scoring_preprocessing.csv')